name: github pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

       - name: Cache Hugo resources
         uses: actions/cache@v4
         with:
           path: |
             ~/.cache/hugo
             pages/resources
           key: ${{ runner.os }}-hugo-${{ hashFiles('pages/**/go.sum') }}
           restore-keys: |
             ${{ runner.os }}-hugo-

      - name: Build
        working-directory: ./pages
        env:
          HUGO_ENV: production
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages/public
